apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - serve
            - --debug
            - --pretty
            - --config=/config/.config.yaml
          env:
            - name: CORE_AUTHZ_HOST_URL
              value: openfga:8080
            - name: CORE_REDIS_ADDRESS
              value: redis:6379
          image: core:dev
          name: api
          ports:
            - containerPort: 17608
              protocol: TCP
          volumeMounts:
            - mountPath: /config/.config.yaml
              name: api-cm0
              subPath: .config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: .config.yaml
                path: .config.yaml
            name: api-cm0
          name: api-cm0
