apiVersion: v1
data:
  .config.yaml: |-
    {{ .Values.api.config | indent 4 }}
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.openlane.service: api
  name: api-cm0
