apiVersion: v1
kind: Service
metadata:
  name: openfga
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "2112"
      port: 2112
      targetPort: 2112
  selector:
    io.openlane.service: openfga
