apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openlane.service: postgres-exporter
    spec:
      containers:
        - env:
            - name: DATA_SOURCE_PASS
              value: password
            - name: DATA_SOURCE_URI
              value: postgres:5432/openfga?sslmode=disable
            - name: DATA_SOURCE_USER
              value: postgres
          image: quay.io/prometheuscommunity/postgres-exporter:latest
          name: postgres-exporter
          ports:
            - containerPort: 9187
              protocol: TCP
      restartPolicy: Always
