apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.openlane.service: redis-data
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
